const nodemailer = require('nodemailer');
const config = require('./config');
const db = require('./db/firebase');

class Rotator {
  constructor(initialConfig = config) { this.config = initialConfig; this.accounts = new Map(); this.rules=[]; this.ruleState = new Map(); this.ready=this.reloadFromFirebase(); this.resetTimer(); }
  async reloadFromFirebase(){ const [accounts,rules,settings]=await Promise.all([db.getAccounts(),db.getRules(),db.getSettings()]); this.config.retry={...this.config.retry,...settings}; this.rules=(rules||[]).map(r=>({...r,match:{subject:r.match?.subject?new RegExp(r.match.subject,'i'):null,from:r.match?.from?new RegExp(r.match.from,'i'):null,to:r.match?.to?new RegExp(r.match.to,'i'):null}})); this.accounts.clear(); (accounts||[]).forEach(acc=>this.accounts.set(acc.id,{config:acc,transporter:nodemailer.createTransport(acc),stats:{sentToday:0,sentHour:0,total:0,errors:0,lastResetDay:Date.now(),lastResetHour:Date.now()}})); this.ruleState.clear(); this.rules.forEach(r=>this.ruleState.set(r.id||r.name,{currentIndex:0})); const stats=await db.getStats(); Object.entries(stats||{}).forEach(([id,s])=>{if(this.accounts.has(id)) this.accounts.get(id).stats={...this.accounts.get(id).stats,...s};}); }
  findRule(email){ return this.rules.find(r=>r.enabled!==false && this.matches(r.match,email)) || this.rules[this.rules.length-1]; }
  matches(match,email){ if(match?.subject && !match.subject.test(email.subject||'')) return false; if(match?.from && !match.from.test(email.from||'')) return false; if(match?.to && !match.to.test(email.to||'')) return false; return true; }
  _isWithinQuota(acc){ return acc.stats.sentToday < (acc.config.dailyLimit||999999) && acc.stats.sentHour < (acc.config.hourlyLimit||999999); }
  _pick(rule){ const list=(rule.accounts||[]).filter(id=>this.accounts.has(id)); const state=this.ruleState.get(rule.id||rule.name)||{currentIndex:0}; for(let i=0;i<list.length;i++){ const idx=(state.currentIndex+i)%list.length; const id=list[idx]; if(this._isWithinQuota(this.accounts.get(id))){ state.currentIndex=(idx+1)%list.length; this.ruleState.set(rule.id||rule.name,state); return id; }} throw new Error('No available account'); }
  findAccountByEmail(email){ for (const [id,acc] of this.accounts.entries()) if ((acc.config.auth?.user||'').toLowerCase()===(email||'').toLowerCase()) return {id,config:acc.config}; return null; }
  async _saveStats(){ const out={}; for(const [id,a] of this.accounts.entries()) out[id]=a.stats; await db.updateStats(out); }
  async sendWithAccount(email,accountId){ await this.ready; const acc=this.accounts.get(accountId); if(!acc) throw new Error('Account not found'); return this._sendByAccount(email,accountId,acc); }
  async _sendByAccount(email,accId,acc){ const payload={...email}; if(acc.config.fromAddress){ const n=acc.config.fromName||acc.config.fromAddress; payload.from=`"${n}" <${acc.config.fromAddress}>`; } const res=await acc.transporter.sendMail(payload); acc.stats.sentToday++;acc.stats.sentHour++;acc.stats.total++; await this._saveStats(); return {success:true,accId,messageId:res.messageId}; }
  async send(email){ await this.ready; const rule=this.findRule(email); let err; for(let i=0;i<=this.config.retry.maxAttempts;i++){ try{const id=this._pick(rule); return await this._sendByAccount(email,id,this.accounts.get(id));}catch(e){err=e; if(i<this.config.retry.maxAttempts) await new Promise(r=>setTimeout(r,this.config.retry.delayMs*(this.config.retry.exponentialBackoff?2**i:1)));}} throw err; }
  resetTimer(){ setInterval(async()=>{ const now=new Date(); for(const a of this.accounts.values()){ const d=new Date(a.stats.lastResetDay); const h=new Date(a.stats.lastResetHour); if(d.toDateString()!==now.toDateString()){a.stats.sentToday=0;a.stats.lastResetDay=Date.now();} if(h.getHours()!==now.getHours()){a.stats.sentHour=0;a.stats.lastResetHour=Date.now();} } await this._saveStats(); },60000); }
}
module.exports = Rotator;
